### ISSUE TITLE
incremental import

### ISSUE THREAD

**Issue by BenLubar** [BenLubar/nodebb-plugin-import-discourse#2]
@pauljherring would it be better to have "import X with IDs higher than Y" or "import X with created_at later than Y"?

**Comment by akhoury** [comment]
+1 
timestamps probably are a better option, semantically.

**Comment by BenLubar** [comment]
https://github.com/BenLubar/nodebb-plugin-import-discourse/blob/12bbd043cf2f63a05d4e0c78568971d0a6a0d84f/index.js#L10-L24

We now support timestamps, IDs, and custom WHERE clauses.
