### ISSUE TITLE
Any documentation on how to use this?  Does it still work?

### ISSUE THREAD

**Issue by ghost** [BenLubar/nodebb-plugin-import-discourse#6]
Any documentation on how to use this?  Does it still work?

**Comment by BenLubar** [comment]
The documentation I created back in March is here: https://docs.google.com/document/d/1YKBtxUtrueaV3STi2RJuN07SZD9_tk4o-b3gwMXvybc/edit#heading=h.rw6mn9bkpczj

As for whether it still works, that depends on whether Discourse has changed their database structure in the last three months.

**Comment by ghost** [comment]
Thanks!

On Wed, Jun 22, 2016 at 1:27 AM, Ben Lubar notifications@github.com wrote:

> The documentation I created back in March is here:
> https://docs.google.com/document/d/1YKBtxUtrueaV3STi2RJuN07SZD9_tk4o-b3gwMXvybc/edit#heading=h.rw6mn9bkpczj
> 
> As for whether it still works, that depends on whether Discourse has
> changed their database structure in the last three months.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/BenLubar/nodebb-plugin-import-discourse/issues/6#issuecomment-227647152,
> or mute the thread
> https://github.com/notifications/unsubscribe/ABn9oTYc_m5a7Wd3oVaI7szHNWRbou3Jks5qOMfLgaJpZM4I7ThZ
> .

## 

nofacepress.com
